// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Elements.Geometry.Solids;
using Elements.Validators;
using Elements.Serialization.JSON;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using System;
using System.Collections.Generic;
using System.Linq;
using Line = Elements.Geometry.Line;
using Polygon = Elements.Geometry.Polygon;

namespace LevelsFromEnvelopes
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v12.0.0.0)")]
    
    public  class LevelsFromEnvelopesInputs : S3Args
    
    {
        [Newtonsoft.Json.JsonConstructor]
        
        public LevelsFromEnvelopesInputs(IList<double> @baseLevels, string bucketName, string uploadsBucket, Dictionary<string, string> modelInputKeys, string gltfKey, string elementsKey, string ifcKey):
        base(bucketName, uploadsBucket, modelInputKeys, gltfKey, elementsKey, ifcKey)
        {
            var validator = Validator.Instance.GetFirstValidatorForType<LevelsFromEnvelopesInputs>();
            if(validator != null)
            {
                validator.PreConstruct(new object[]{ @baseLevels});
            }
        
            this.BaseLevels = @baseLevels;
        
            if(validator != null)
            {
                validator.PostConstruct(this);
            }
        }
    
        /// <summary>Supply a list of level floor-to-floor heights. The last supplied value will be treated as the typical level height and repeated until the top level.</summary>
        [Newtonsoft.Json.JsonProperty("Base Levels", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public IList<double> BaseLevels { get; set; }
    
    
    }
}