// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Elements.Geometry.Solids;
using Elements.Validators;
using Elements.Serialization.JSON;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using System;
using System.Collections.Generic;
using System.Linq;
using Line = Elements.Geometry.Line;
using Polygon = Elements.Geometry.Polygon;

namespace EnvolopeByPolyline
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v12.0.0.0)")]
    
    public  class EnvolopeByPolylineInputs : S3Args
    
    {
        [Newtonsoft.Json.JsonConstructor]
        
        public EnvolopeByPolylineInputs(double @buildingWidth, Polyline @buildingAxis, double @buildingHeight, string bucketName, string uploadsBucket, Dictionary<string, string> modelInputKeys, string gltfKey, string elementsKey, string ifcKey):
        base(bucketName, uploadsBucket, modelInputKeys, gltfKey, elementsKey, ifcKey)
        {
            var validator = Validator.Instance.GetFirstValidatorForType<EnvolopeByPolylineInputs>();
            if(validator != null)
            {
                validator.PreConstruct(new object[]{ @buildingWidth, @buildingAxis, @buildingHeight});
            }
        
            this.BuildingWidth = @buildingWidth;
            this.BuildingAxis = @buildingAxis;
            this.BuildingHeight = @buildingHeight;
        
            if(validator != null)
            {
                validator.PostConstruct(this);
            }
        }
    
        /// <summary>The width of the building</summary>
        [Newtonsoft.Json.JsonProperty("Building Width", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double BuildingWidth { get; set; } = 18D;
    
        /// <summary>A planar continuous set of lines defining the general axis of the building</summary>
        [Newtonsoft.Json.JsonProperty("Building Axis", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Polyline BuildingAxis { get; set; }
    
        /// <summary>The height of the building</summary>
        [Newtonsoft.Json.JsonProperty("Building Height", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double BuildingHeight { get; set; } = 10D;
    
    
    }
}